version: '3.1'

services:
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped
  db:
    env_file: .env.local
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
