version: '3.1'

services:
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

  cms:
    depends_on:
      - db
    env_file: .env.local
    image: strapi/strapi
    restart: unless-stopped
    volumes:
      - ./cms:/srv/app
    ports:
      - 1337:1337

  db:
    env_file: .env.local
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  data:
